Repository zeppelinos/zos-lib, pull requests merged in 2018-06, with the labels that each got.

#164 Fix solidity-coverage
  .solcover.js
  package.json
  scripts/test.sh
  src/utils/Contracts.js
  truffle-config.js
Labels: status:review

#170 Improve tests coverage
  src/test/behaviors/ImplementationDirectory.js
  test/contracts/migrations/Migratable.test.js
Labels: kind:tests, status:review

#152 Added regression tests
  contracts/mocks/RegressionImplementation.sol
  test/contracts/upgradeability/AdminUpgradeabilityProxy.test.js
Labels: status:in progress

#168 Remove Release contract
  contracts/application/AppDirectory.sol
  contracts/application/BaseApp.sol
  contracts/application/versioning/FreezableImplementationDirectory.sol
  contracts/application/versioning/Release.sol
  examples/complex/test/App.test.js
  src/app/App.js
  src/app/AppDeployer.js
  src/app/AppProvider.js
  src/directory/AppDirectory.js
  src/directory/AppDirectoryDeployer.js
  src/directory/AppDirectoryProvider.js
  src/directory/FreezableImplementationDirectory.js
  src/directory/ImplementationDirectory.js
  src/directory/ImplementationDirectoryDeployer.js
  src/index.js
  src/package/Package.js
  src/package/PackageDeployer.js
  src/package/PackageProvider.js
  src/package/PackageWithAppDirectories.js
  src/package/PackageWithFreezableDirectories.js
  src/package/PackageWithNonFreezableDirectories.js
  src/release/Release.js
  src/test/behaviors/ImplementationDirectory.js
  src/utils/Contracts.js
  test/contracts/application/AppDirectory.test.js
  test/contracts/application/versioning/FreezableImplementationDirectory.test.js
  test/contracts/application/versioning/ImplementationDirectory.test.js
  test/contracts/application/versioning/Release.test.js
  test/src/app/App.test.js
  test/src/directory/AppDirectory.test.js
  test/src/directory/FreezableImplementationDirectory.test.js
  test/src/directory/ImplementationDirectory.test.js
  test/src/package/Package.test.js
  test/src/package/PackageWithAppDirectories.test.js
  test/src/package/PackageWithFreezableDirectories.test.js
  test/src/package/PackageWithNonFreezableDirectories.test.js
  test/src/release/Release.test.js
Labels: status:review
