Repository zeppelinos/zos-lib, pull requests merged in 2018-04, with the labels that each got.

#13 Improve proxy's fallback gas cost
  contracts/upgradeability/Proxy.sol
Labels: enhancement

#29 Added TravisCI coverage tests
  .gitignore
  .solcover.js
  .travis.yml
  package-lock.json
  package.json
  readme.md
  scripts/test.sh
  truffle-config.js
Labels: kind:chore, kind:minor, kind:tests

#35 Improve tests coverage
  contracts/ProjectController.sol
  contracts/mocks/InitializableMock.sol
  contracts/upgradeability/OwnedUpgradeabilityProxy.sol
  contracts/upgradeability/UpgradeabilityProxy.sol
  test/Initializable.test.js
  test/ProjectController.test.js
  test/helpers/encodeCall.js
  test/upgradeability/OwnedUpgradeabilityProxy.js
  test/upgradeability/UpgradeabilityProxyFactory.test.js
Labels: kind:enhancement, kind:tests

#42 Refactor project controller to work with a single distribution
  contracts/ImplementationProvider.sol
  contracts/ProjectController.sol
  contracts/Registry.sol
  contracts/application/management/AppDirectory.sol
  contracts/application/management/BaseAppManager.sol
  contracts/application/management/PackagedAppManager.sol
  contracts/application/management/UnversionedAppManager.sol
  contracts/application/versioning/ContractDirectory.sol
  contracts/application/versioning/ContractProvider.sol
  contracts/application/versioning/FreezableContractDirectory.sol
  contracts/application/versioning/Package.sol
  contracts/mocks/ImplementationProviderMock.sol
  contracts/mocks/InitializableMock.sol
  test/ProjectController.test.js
  test/Registry.test.js
  test/application/management/AppDirectory.test.js
  test/application/management/PackagedAppManager.test.js
  test/application/management/UnversionedAppManager.test.js
  test/application/versioning/ContractDirectory.behavior.js
  test/application/versioning/ContractDirectory.test.js
  test/application/versioning/FreezableContractDirectory.test.js
  test/application/versioning/Package.test.js
  truffle-config.js
Labels: kind:enhancement, status:in progress, topic:upgradeability

#40 Migratable behaviour
  contracts/migrations/Initializable.sol
  contracts/migrations/Migratable.sol
  contracts/mocks/InitializableMock.sol
  contracts/mocks/MultipleInheritanceMigratableMocks.sol
  contracts/mocks/SingleInheritanceMigratableMocks.sol
  package-lock.json
  package.json
  test/application/management/PackagedAppManager.test.js
  test/application/management/UnversionedAppManager.test.js
  test/helpers/decodeLogs.js
  test/migrations/Initializable.test.js
  test/migrations/Migratable.test.js
  test/upgradeability/OwnedUpgradeabilityProxy.js
  test/upgradeability/OwnedUpgradeabilityProxy.test.js
Labels: kind:enhancement, topic:upgradeability

#54 Require OwnedUpgradeabilityProxy contracts to receive an initial implementation on construction time
  contracts/mocks/DummyImplementation.sol
  contracts/upgradeability/OwnedUpgradeabilityProxy.sol
  contracts/upgradeability/Proxy.sol
  contracts/upgradeability/UpgradeabilityProxy.sol
  contracts/upgradeability/UpgradeabilityProxyFactory.sol
  test/application/management/PackagedAppManager.test.js
  test/application/management/UnversionedAppManager.test.js
  test/migrations/Migratable.test.js
  test/upgradeability/OwnedUpgradeabilityProxy.test.js
Labels: kind:discussion, kind:enhancement, topic:upgradeability
